### ISSUE TITLE
[REQUEST] 작가정보페이지 수정요청

### ISSUE THREAD

**Issue by NYANGSoobeen** [ImMin5/CULIFE#153]
PR시 close를 사용하여 포함 시켜 주세요.

- 작가소개textarea 리사이징 막아주세요.
- 작가소개 스크롤시 글자 겹치지 않게 해주세요
- 프로필 설정 마우스 오버 시 cursor:pointer 되도록 해주세요.
- 작가소개 100자 이상 넘어가면 뜨는 에러 메시지 수정 부탁드립니다.
- 전체적으로 내려와 보여서 위에 여백 조금만 줄여주세요.

**Comment by ImMin5** [comment]
작가소개 스크롤시 글자 겹치지 않게 해주세요 -> 해결 못함
