### ISSUE TITLE
[REQUEST] 온라인전시회 - 작가 검색 기능 수정

### ISSUE THREAD

**Issue by ImMin5** [ImMin5/CULIFE#178]
PR시 close를 사용하여 포함 시켜 주세요.

- 검색 후 검색 단어가 초기화됨
 
![image](https://user-images.githubusercontent.com/38625842/169223103-9da1d814-e8fb-4c02-8b17-2bacf1202c5b.png)
![image](https://user-images.githubusercontent.com/38625842/169222991-97c349de-c187-48c5-96ce-6c1596e06efa.png)

- 검색단어 없을 시 검색이 안됨

**Comment by NYANGSoobeen** [comment]
해결했습니다.
