### ISSUE TITLE
[🐞 버그] warngin_count 들어간 mapper 수정 요청

### ISSUE THREAD

**Issue by ImMin5** [ImMin5/CULIFE#188]
## 설명
warning_count가 들어간 mapper에서 계속 오류 메세지가 뜸
## 담당자
@jiyy97 
@HyeonjooJang 

## 버그 에러코드
에러 코드나 스크린샷 첨부
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/38625842/169467967-7dd460cc-0475-4eb6-bed4-b37a3c7ad605.png">

**Comment by kwonjiy** [comment]
수정했습니당!
