### ISSUE TITLE
[의논] 작가 상세정보 페이지

### ISSUE THREAD

**Issue by ImMin5** [ImMin5/CULIFE#72]

**Comment by NYANGSoobeen** [comment]
<작가목록 / 작가검색>
![image](https://user-images.githubusercontent.com/96978871/167519867-695f786b-a17a-4eb5-b634-c83cb4ba2d89.png)

<작가 상세 페이지>
![image](https://user-images.githubusercontent.com/96978871/167519932-68336bba-dbc0-4a7e-b01b-bcf7928a683e.png)

<작가 작품 상세 - 모달>
![image](https://user-images.githubusercontent.com/96978871/167519950-e0ae4274-7089-42e7-b637-4da41bfced45.png)
